it does seem somewhat harsh just to
curtail
this
very
small
amount.
curtail this very small amount.
Clare's
brutal
question
was,
what
Clare's brutal question was, what
would
you
say
to
the
ones
not
would you say to the ones not
allowed
in?
What
do
you
actually
allowed in?
What do you actually
say?
It
is
very
difficult.
One
has
say? It is very difficult. One has
to
be
quite
clear
about
this,
and.
to be quite clear about this, and.